"""Build the sidecar (onedir) and stage it for Tauri.

Runs PyInstaller against sidecar.spec (onedir: exe + _internal/), then stages
into the Tauri project's binaries/ folder:

    src-tauri/binaries/fflogs-efficiency-analyzer-sidecar-<triple>.exe
        — the exe, target-triple-suffixed for Tauri's bundle.externalBin
          (Tauri strips the triple at bundle time, so it installs next to
          the app exe as fflogs-efficiency-analyzer-sidecar.exe)
    src-tauri/binaries/_internal/
        — PyInstaller's dependency tree, bundled via bundle.resources so it
          lands at the install root adjacent to the exe (on Windows the
          Tauri resource dir IS the install root)

binaries/ is wiped before staging — it is fully generated and gitignored.

The exe gets a Windows version resource generated from tauri.conf.json's
version (NSIS can skip replacing version-less exes on update).

Usage (from the repo root):
    python python/sidecar/build_sidecar.py

Env overrides:
    UI_PROJECT=...path to repo root containing src-tauri/...
    TAURI_TARGET_TRIPLE=x86_64-pc-windows-msvc
    SIDECAR_SKIP_SMOKE=1      skip the staged-exe --selftest-pool smoke run
    SIDECAR_SIGN_COMMAND=...  optional code-sign hook run against the staged
                              exe; "{path}" is replaced with the exe path,
                              e.g.  signtool sign /fd sha256 ... "{path}"
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = Path(__file__).parent / "sidecar.spec"

UI_PROJECT = Path(os.environ.get("UI_PROJECT", str(ROOT.parent)))
TARGET_TRIPLE = os.environ.get("TAURI_TARGET_TRIPLE", "x86_64-pc-windows-msvc")

NAME = "fflogs-efficiency-analyzer-sidecar"
BUILT_DIR = ROOT / "dist" / NAME
BUILT_EXE = BUILT_DIR / f"{NAME}.exe"
BUILT_INTERNAL = BUILT_DIR / "_internal"
BINARIES_DIR = UI_PROJECT / "src-tauri" / "binaries"
TARGET_EXE = BINARIES_DIR / f"{NAME}-{TARGET_TRIPLE}.exe"
TARGET_INTERNAL = BINARIES_DIR / "_internal"
TAURI_CONF = UI_PROJECT / "src-tauri" / "tauri.conf.json"
VERSION_FILE = ROOT / "build" / "sidecar_version_info.txt"


def _app_version() -> str:
    try:
        return json.loads(TAURI_CONF.read_text(encoding="utf-8"))["version"]
    except Exception as e:  # noqa: BLE001 - version resource is best-effort
        print(f"!! could not read version from {TAURI_CONF}: {e}", file=sys.stderr)
        return "0.0.0"


def _write_version_file(version: str) -> Path:
    """PyInstaller VSVersionInfo file so the exe carries a Windows version
    resource matching the app version."""
    parts = [int(p) for p in (version.split(".") + ["0", "0", "0"])[:3] if p.isdigit()]
    while len(parts) < 3:
        parts.append(0)
    tup = f"({parts[0]}, {parts[1]}, {parts[2]}, 0)"
    quad = f"{parts[0]}.{parts[1]}.{parts[2]}.0"
    content = f"""# Generated by build_sidecar.py from tauri.conf.json — do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup},
    prodvers={tup},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('FileDescription', 'Meridian analyzer sidecar'),
        StringStruct('FileVersion', '{quad}'),
        StringStruct('InternalName', '{NAME}'),
        StringStruct('OriginalFilename', '{NAME}.exe'),
        StringStruct('ProductName', 'Meridian'),
        StringStruct('ProductVersion', '{quad}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""
    VERSION_FILE.parent.mkdir(parents=True, exist_ok=True)
    VERSION_FILE.write_text(content, encoding="utf-8")
    return VERSION_FILE


def _smoke_test() -> int:
    """Run the staged exe's --selftest-pool: proves the frozen onedir exe boots
    from the staged layout (triple-suffixed name, _internal/ sibling) and that
    multiprocessing spawn works (or cleanly falls back)."""
    print(">> smoke: --selftest-pool on the staged exe")
    rc = subprocess.call([str(TARGET_EXE), "--selftest-pool"], cwd=str(BINARIES_DIR))
    if rc != 0:
        print(f"!! staged sidecar selftest failed (rc={rc})", file=sys.stderr)
    return rc


def main() -> int:
    version = _app_version()
    vfile = _write_version_file(version)
    print(f">> PyInstaller build (root={ROOT}, version={version})")
    env = dict(os.environ, SIDECAR_VERSION_FILE=str(vfile))
    rc = subprocess.call(
        [sys.executable, "-m", "PyInstaller", "--clean", "--noconfirm", str(SPEC)],
        cwd=str(ROOT),
        env=env,
    )
    if rc != 0:
        print(f"!! PyInstaller exited {rc}", file=sys.stderr)
        return rc

    if not BUILT_EXE.exists() or not BUILT_INTERNAL.is_dir():
        print(f"!! expected onedir output at {BUILT_DIR} not found", file=sys.stderr)
        return 1

    # binaries/ is fully generated (and gitignored) — wipe so stale onefile
    # exes / renamed leftovers never ride along into a bundle.
    if BINARIES_DIR.exists():
        shutil.rmtree(BINARIES_DIR)
    BINARIES_DIR.mkdir(parents=True)
    shutil.copy2(BUILT_EXE, TARGET_EXE)
    shutil.copytree(BUILT_INTERNAL, TARGET_INTERNAL)
    n_files = sum(1 for p in TARGET_INTERNAL.rglob("*") if p.is_file())
    print(f">> staged: {TARGET_EXE}")
    print(f">> staged: {TARGET_INTERNAL} ({n_files} files)")

    sign_cmd = os.environ.get("SIDECAR_SIGN_COMMAND", "").strip()
    if sign_cmd:
        cmd = sign_cmd.replace("{path}", str(TARGET_EXE))
        print(f">> signing staged exe: {cmd}")
        rc = subprocess.call(cmd, shell=True)
        if rc != 0:
            print(f"!! sign command exited {rc}", file=sys.stderr)
            return rc

    if os.environ.get("SIDECAR_SKIP_SMOKE") != "1":
        rc = _smoke_test()
        if rc != 0:
            return rc

    return 0


if __name__ == "__main__":
    sys.exit(main())
